In [1]:
import pandas as pd
import numpy as np

In [2]:
obj = pd.Series([4, 7, -5, 3])

In [3]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [4]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [5]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [6]:
obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])

In [7]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [8]:
 obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [9]:
obj2.values

array([ 4,  7, -5,  3], dtype=int64)

In [10]:
obj2['a'] = 100

In [11]:
obj2.values

array([  4,   7, 100,   3], dtype=int64)

In [12]:
obj2[['c', 'a', 'd']]

c      3
a    100
d      4
dtype: int64

In [13]:
obj2[obj2>90]

a    100
dtype: int64

In [14]:
np.exp(obj2)

d    5.459815e+01
b    1.096633e+03
a    2.688117e+43
c    2.008554e+01
dtype: float64

In [15]:
'b' in obj2

True

In [16]:
4 in obj2

False

In [17]:
obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])


In [18]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [19]:
obj2['a']

-5

In [20]:
obj2[obj2 > 0]

d    4
b    7
c    3
dtype: int64

In [21]:
 obj2 * 2

d     8
b    14
a   -10
c     6
dtype: int64

In [22]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [23]:
np.exp(obj2)

d      54.598150
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [24]:
#common way to create dataframe is to use dict by key , value pairs
data = {'state': ['Ohio', 'Ohio', 'Nevada'],
       'year': [2000, 2003, 2004],
       'pop': [1.4, 1.5, 1.6]}

In [25]:
frame = pd.DataFrame(data)

In [26]:
frame

state  year  pop
0    Ohio  2000  1.4
1    Ohio  2003  1.5
2  Nevada  2004  1.6

In [27]:
pd.DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.4
1  2003    Ohio  1.5
2  2004  Nevada  1.6

In [28]:
frame['state']

0      Ohio
1      Ohio
2    Nevada
Name: state, dtype: object

In [29]:
frame.loc[2]

state    Nevada
year       2004
pop         1.6
Name: 2, dtype: object

In [30]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])

In [31]:
val

two    -1.2
four   -1.5
five   -1.7
dtype: float64

In [32]:
frame['eastern'] = frame.state == 'Ohio'

In [33]:
frame

state  year  pop  eastern
0    Ohio  2000  1.4     True
1    Ohio  2003  1.5     True
2  Nevada  2004  1.6    False

In [34]:
frame['western'] = frame.state == 'Nevada'

In [35]:
frame

state  year  pop  eastern  western
0    Ohio  2000  1.4     True    False
1    Ohio  2003  1.5     True    False
2  Nevada  2004  1.6    False     True

In [36]:
del frame['western']

In [37]:
frame

state  year  pop  eastern
0    Ohio  2000  1.4     True
1    Ohio  2003  1.5     True
2  Nevada  2004  1.6    False

In [38]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
....: 'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [39]:
pop

{'Nevada': {2001: 2.4, 2002: 2.9}, 'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [40]:
frame3 = pd.DataFrame(pop)

In [41]:
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [42]:
frame3.T

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [43]:
pop

{'Nevada': {2001: 2.4, 2002: 2.9}, 'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [44]:
pd.DataFrame(pop, index=[2002, 2001, 2003])

Nevada  Ohio
2002     2.9   3.6
2001     2.4   1.7
2003     NaN   NaN

In [45]:
 pdata = {'Ohio': frame3['Ohio'][:-1],
....: 'Nevada': frame3['Nevada'][:2]}

In [46]:
pdata

{'Ohio': 2001    1.7
 2002    3.6
 Name: Ohio, dtype: float64,
 'Nevada': 2001    2.4
 2002    2.9
 Name: Nevada, dtype: float64}

In [47]:
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [48]:
frame3.index.name = 'year'; frame3.columns.name = 'state'

In [49]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [50]:
frame3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [51]:
#Index Objects in pandas

In [52]:
obj = pd.Series(range(3), index=['a', 'b', 'c'])

In [53]:
obj

a    0
b    1
c    2
dtype: int64

In [54]:
index = obj.index

In [55]:
index

Index(['a', 'b', 'c'], dtype='object')

In [56]:
index[1:]

Index(['b', 'c'], dtype='object')

In [57]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [58]:
'Ohio' in frame3.columns

True

In [59]:
2003 in frame3.index

False

In [60]:
#can make duplicate labels
dup_labels = pd.Index(['foo', 'foo', 'bar', 'bar', 'a'])

In [61]:
dup_labels

Index(['foo', 'foo', 'bar', 'bar', 'a'], dtype='object')

In [62]:
index

Index(['a', 'b', 'c'], dtype='object')

In [63]:
index.append(dup_labels)

Index(['a', 'b', 'c', 'foo', 'foo', 'bar', 'bar', 'a'], dtype='object')

In [64]:
index.intersection(dup_labels)

Index(['a'], dtype='object')

In [65]:
index.union(dup_labels)

Index(['a', 'b', 'bar', 'bar', 'c', 'foo', 'foo'], dtype='object')

In [66]:
index.isin(dup_labels)

array([ True, False, False])

In [67]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])

In [68]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [69]:
obj2 = obj2.reindex(['a', 'b', 'c', 'd'])

In [70]:
obj2

a   -5
b    7
c    3
d    4
dtype: int64

In [71]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])

In [72]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [73]:
obj3.reindex(range(6), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [74]:
frame = pd.DataFrame(np.arange(9).reshape(3,3),
                    index=['a', 'b', 'c'],
                    columns=['Ohio', 'Nevada', 'texas'])

In [75]:
frame

Ohio  Nevada  texas
a     0       1      2
b     3       4      5
c     6       7      8

In [76]:
states = ['Ohio', 'texas','Ohio', 'Nevada']


In [77]:
frame.reindex(columns=states)

Ohio  texas  Ohio  Nevada
a     0      2     0       1
b     3      5     3       4
c     6      8     6       7

In [78]:
frame.loc[['a', 'b', 'c'], states]

Ohio  texas  Ohio  Nevada
a     0      2     0       1
b     3      5     3       4
c     6      8     6       7

In [79]:
frame.T

a  b  c
Ohio    0  3  6
Nevada  1  4  7
texas   2  5  8

In [80]:
#droping entries from axis
obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])

In [81]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [82]:
new_obj = obj.drop('c')

In [83]:
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [84]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
.....: index=['Ohio', 'Colorado', 'Utah', 'New York'],
.....: columns=['one', 'two', 'three', 'four'])


In [85]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [86]:
data.drop('Ohio')

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [87]:
data.drop('two', axis='columns')

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [88]:
data.drop('four', axis=1)

one  two  three
Ohio        0    1      2
Colorado    4    5      6
Utah        8    9     10
New York   12   13     14

In [89]:
obj = pd.Series(np.arange(4.), index=['a', 'b', 'c', 'd'])


In [90]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [91]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [92]:
obj[['b','a','d']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [93]:
obj[[1, 2]]

b    1.0
c    2.0
dtype: float64

In [94]:
obj[obj<2]

a    0.0
b    1.0
dtype: float64

In [95]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [96]:
obj['a':'c']

a    0.0
b    1.0
c    2.0
dtype: float64

In [97]:
obj['a':'c'] = 5

In [98]:
obj

a    5.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [99]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
.....: index=['Ohio', 'Colorado', 'Utah', 'New York'],
.....: columns=['one', 'two', 'three', 'four'])

In [100]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [101]:
data[['three', 'four']]

three  four
Ohio          2     3
Colorado      6     7
Utah         10    11
New York     14    15

In [102]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [103]:
data[data['three']>5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [104]:
data.iloc[0:3]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11

In [105]:
data[0:3]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11

In [106]:
data[data<5]=0

In [107]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [108]:
data.loc['Colorado', ['two', 'three']]

two      5
three    6
Name: Colorado, dtype: int32

In [109]:
data.loc[:'Utah',['one','two']]

one  two
Ohio        0    0
Colorado    0    5
Utah        8    9

In [110]:
data.iloc[2,[3,0,1]]

four    11
one      8
two      9
Name: Utah, dtype: int32

In [111]:
data.loc['Utah', 'two']

9

In [114]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)),
.....: columns=list('abcd'))
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)),
.....: columns=list('abcde'))


In [117]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [116]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [124]:
df1.loc[1,'b'] = 5

In [125]:
df1.loc[1,'b']

5.0

In [126]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [128]:
df2.loc[1, 'b'] = np.nan

In [129]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [130]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [131]:
df1.add(df2, fill_value = 0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0